const {loadEngine}=require('./load');const DEG=180/Math.PI,G=9.81;const clamp=(v,a,b)=>v<a?a:v>b?b:v;const f=(x,d=2)=>(+x).toFixed(d);
function fresh(surface,lsd,coast){const E=loadEngine();Object.assign(E.cfg,{surface,drive:'awd',auto:true,steer:'direct',uniform:true,profile:false,driven:false});E.VERT.amp=0;if(lsd!==undefined){E.cfg.lsd=lsd;E.cfg.lsdCoast=coast;}E.selectTrack('rundkurs');return E;}
function setSpeed(E,v,gi){const S=E.S,CAR=E.CAR;S.vx=v;S.vy=0;S.r=0;S.delta=0;S.dComp=0;S.psi=0;S.x=0;S.y=0;const w=v/CAR.Rw;S.w=[w,w,w,w];S.gi=gi||3;S.rpm=w*CAR.gears[S.gi].r*CAR.final*9.55;S.we=S.rpm*0.10472;S.shiftLock=0.4;E.vertInit();}
function hold(E,vT,c){const e=vT-Math.hypot(E.S.vx,E.S.vy);c.I=clamp((c.I||0)+e*E.DT*0.6,-0.9,0.9);const u=0.35*e+c.I;E.IN.thr=clamp(u,0,1);E.IN.brk=clamp(-u*0.5,0,1);}
function skid(E){const S=E.S,L=E.CAR.a+E.CAR.b,vT=60/3.6;setSpeed(E,vT);const c={};for(let i=0;i<720;i++){hold(E,vT,c);E.step(E.DT);}let t=0,ayMax=0,past=false;const lin=[];
  while(t<40){const d=0.5/DEG*t;E.IN.steer=d/E.CAR.maxSteer;hold(E,vT,c);E.step(E.DT);t+=E.DT;const ay=S.ay;if(ay>=0.3*G)past=true;if(!past&&ay>0.1*G)lin.push([ay,d]);ayMax=Math.max(ayMax,ay);if(ay<0.9*ayMax&&d*DEG>5)break;}
  const n=lin.length;let sx=0,sy=0,sxx=0,sxy=0;for(const [a,d] of lin){sx+=a;sy+=d;sxx+=a*a;sxy+=a*d;}return {ay:ayMax/G,K:((n*sxy-sx*sy)/(n*sxx-sx*sx)-L/(vT*vT))*G*DEG};}
function stab(E,ayT,act,thr){const S=E.S,vT=60/3.6;setSpeed(E,vT);const c={};for(let i=0;i<720;i++){hold(E,vT,c);E.step(E.DT);}E.IN.steer=((E.CAR.a+E.CAR.b)/(vT*vT)+(2.5/DEG)/G)*ayT*G/E.CAR.maxSteer;for(let i=0;i<1080;i++){hold(E,vT,c);E.step(E.DT);}const r0=S.r;let rMax=r0,bMax=0,kIn=0;for(let i=0;i<360;i++){E.IN.thr=act==='power'?thr:0;E.IN.brk=0;E.step(E.DT);rMax=Math.max(rMax,S.r);bMax=Math.max(bMax,Math.abs(Math.atan2(S.vy,S.vx))*DEG);kIn=Math.max(kIn,S.kappa[2]);}return {dr:(rMax/r0-1)*100,bMax,kIn};}
function lap(E){const S=E.S,T=E.TRACK;let t=0,laps=0,prevS=T.pts[S.idx].s,tLap=null,off=0;E.cfg.profile=true;E.cfg.driven=true;E.VERT.amp=1;E.selectTrack('rundkurs');
  while(t<240&&laps<2){E.ghostAI();E.step(E.DT);t+=E.DT;const s=T.pts[S.idx].s;if(s<prevS-800){laps++;if(laps===1)tLap=t;if(laps===2)tLap=t-tLap;}prevS=s;if(laps>=1&&!S.onTrack)off+=E.DT;}return {tLap,off};}
console.log((process.env.ENGINE||'engine.js')+'  AWD  lock',process.argv[2]||'default');
const lsd=process.argv[2]?+process.argv[2]:undefined,coast=process.argv[3]?+process.argv[3]:undefined;
for(const surface of ['gravel','tarmac']){const s=skid(fresh(surface,lsd,coast)),p=stab(fresh(surface,lsd,coast),0.45,'power',1),p6=stab(fresh(surface,lsd,coast),0.45,'power',0.6),l=stab(fresh(surface,lsd,coast),surface==='tarmac'?0.6:0.45,'lift',0),lp=lap(fresh(surface,lsd,coast));
  console.log('  '+surface.padEnd(7),'skidpad',f(s.ay),'g K',f(s.K,1),'| power 100%: dr',f(p.dr,0)+'%','b',f(p.bMax,0)+'°','kIn',f(p.kIn),'| power 60%: dr',f(p6.dr,0)+'%','b',f(p6.bMax,0)+'°','| lift dr',f(l.dr,0)+'%','| phantom lap',f(lp.tLap,1),'s off',f(lp.off,1));}
