const {loadEngine}=require('./load');const DEG=180/Math.PI,G=9.81;const clamp=(v,a,b)=>v<a?a:v>b?b:v;const f=(x,d=2)=>(+x).toFixed(d);
const SET={'previous RWD default':{lsd:0.60,lsdCoast:0.40,roll:0.48,toeR:0.25,rs:0.14,toeF:-0.10,rollGrad:3.2,dmp:1.0,bias:0.76},'new RWD default':null,
 'forgiving':{lsd:0.78,lsdCoast:0.52,roll:0.57,toeR:0.40,rs:0.20,toeF:0.05,rollGrad:3.8,dmp:1.25,bias:0.80},'RWD drift':'tpl'};
function fresh(surface,name){const E=loadEngine();Object.assign(E.cfg,{surface,drive:'rwd',auto:true,steer:'direct',uniform:true,profile:false,driven:false});E.VERT.amp=0;E.applyDriveSetup('rwd');const s=SET[name];
  if(s==='tpl')E.applySetupTemplate('RWD drift');else if(s){E.cfg.lsd=s.lsd;E.cfg.lsdCoast=s.lsdCoast;E.cfg.roll=s.roll;E.cfg.rollGrad=s.rollGrad;E.cfg.bias=s.bias;E.VERT.dmpScale=s.dmp;E.CAR.toeF=s.toeF/DEG;E.CAR.toeR=s.toeR/DEG;E.CAR.bsR=s.rs*2/E.CAR.tR;if(E.rollBars)E.rollBars();}
  E.selectTrack('rundkurs');return E;}
function setSpeed(E,v,gi){const S=E.S,CAR=E.CAR;S.vx=v;S.vy=0;S.r=0;S.delta=0;S.dComp=0;S.psi=0;S.x=0;S.y=0;const w=v/CAR.Rw;S.w=[w,w,w,w];S.gi=gi||3;S.rpm=w*CAR.gears[S.gi].r*CAR.final*9.55;S.we=S.rpm*0.10472;S.shiftLock=0.4;E.vertInit();}
function hold(E,vT,c){const e=vT-Math.hypot(E.S.vx,E.S.vy);c.I=clamp((c.I||0)+e*E.DT*0.6,-0.9,0.9);const u=0.35*e+c.I;E.IN.thr=clamp(u,0,1);E.IN.brk=clamp(-u*0.5,0,1);}
function skid(E){const S=E.S,L=E.CAR.a+E.CAR.b,vT=60/3.6;setSpeed(E,vT);const c={};for(let i=0;i<720;i++){hold(E,vT,c);E.step(E.DT);}let t=0,ayMax=0,inR=1e9,past=false;const lin=[];
  while(t<40){const d=0.5/DEG*t;E.IN.steer=d/E.CAR.maxSteer;hold(E,vT,c);E.step(E.DT);t+=E.DT;const ay=S.ay;if(ay>=0.3*G)past=true;if(!past&&ay>0.1*G)lin.push([ay,d]);if(ay>ayMax){ayMax=ay;inR=S.Fz[2];}if(ay<0.9*ayMax&&d*DEG>5)break;}
  const n=lin.length;let sx=0,sy=0,sxx=0,sxy=0;for(const [a,d] of lin){sx+=a;sy+=d;sxx+=a*a;sxy+=a*d;}return {ay:ayMax/G,inR,K:((n*sxy-sx*sy)/(n*sxx-sx*sx)-L/(vT*vT))*G*DEG};}
function stab(E,thr){const S=E.S,vT=60/3.6;setSpeed(E,vT);const c={};for(let i=0;i<720;i++){hold(E,vT,c);E.step(E.DT);}E.IN.steer=((E.CAR.a+E.CAR.b)/(vT*vT)+(2/DEG)/G)*0.45*G/E.CAR.maxSteer;for(let i=0;i<1080;i++){hold(E,vT,c);E.step(E.DT);}const r0=S.r;let rMax=r0,bMax=0;for(let i=0;i<360;i++){E.IN.thr=thr;E.IN.brk=0;E.step(E.DT);rMax=Math.max(rMax,S.r);bMax=Math.max(bMax,Math.abs(Math.atan2(S.vy,S.vx))*DEG);}return {dr:(rMax/r0-1)*100,bMax};}
function human(E){const S=E.S,CAR=E.CAR,vT=60/3.6;setSpeed(E,vT);const c={};for(let i=0;i<720;i++){hold(E,vT,c);E.step(E.DT);}const steer0=((CAR.a+CAR.b)/(vT*vT)+(2/DEG)/G)*0.45*G/CAR.maxSteer;E.IN.steer=steer0;for(let i=0;i<1080;i++){hold(E,vT,c);E.step(E.DT);}
  let t=0,bMax=0,tOut=null,sw=steer0,spun=false;for(let i=0;i<Math.round(4/E.DT);i++){const b=Math.atan2(S.vy,Math.abs(S.vx)),bd=b*DEG;if(t<0.5){E.IN.thr=1;E.IN.steer=steer0;}else{if(tOut===null&&Math.abs(bd)>5)tOut=t;if(tOut!==null&&t>tOut+0.25){const target=clamp(1.2*b/CAR.maxSteer,-300/(CAR.lock/2),300/(CAR.lock/2));const rate=500/(CAR.lock/2)*E.DT;sw+=clamp(target-sw,-rate,rate);E.IN.steer=sw;E.IN.thr=0;}else{E.IN.steer=steer0;E.IN.thr=1;}}
    E.step(E.DT);t+=E.DT;bMax=Math.max(bMax,Math.abs(bd));if(Math.abs(bd)>90)spun=true;}return {bMax,spun};}
function catchS(E,vk){const S=E.S;setSpeed(E,vk/3.6);let t=0,bMax=0,rec=null;for(let i=0;i<Math.round(4/E.DT);i++){const b=Math.atan2(S.vy,Math.abs(S.vx));if(t<0.7){E.IN.steer=0.6;E.IN.thr=1;}else{E.IN.steer=clamp(1.2*b/E.CAR.maxSteer,-1,1);E.IN.thr=0;}E.step(E.DT);t+=E.DT;bMax=Math.max(bMax,Math.abs(b)*DEG);if(t>0.7&&rec===null&&Math.abs(b)*DEG<5&&bMax>10)rec=t-0.7;}return {bMax,rec};}
console.log('RWD setup                 surface | skidpad ay  inside-rear N  K °/g | stab 100% dr  beta | stab 60% dr beta | human catch beta | ideal catch 40: beta/t');
for(const name of Object.keys(SET))for(const surface of ['tarmac','gravel']){const s=skid(fresh(surface,name)),p1=stab(fresh(surface,name),1),p6=stab(fresh(surface,name),0.6),h=human(fresh(surface,name)),c=catchS(fresh(surface,name),40);
  console.log(name.padEnd(22),surface.padEnd(7),'|',f(s.ay),'  ',f(s.inR,0).padStart(5),'   ',f(s.K,1).padStart(5),'|',f(p1.dr,0).padStart(5)+'%',f(p1.bMax,0).padStart(3)+'°','|',f(p6.dr,0).padStart(4)+'%',f(p6.bMax,0).padStart(3)+'°','|',(h.spun?'SPIN':f(h.bMax,0)+'°').padStart(5),'|',f(c.bMax,0)+'°/'+(c.rec!==null?f(c.rec,1)+'s':'never'));}
