// Measure the setup templates: skidpad limit and inside-rear load, braking, launch, catch, lift-off, power stab.
const {loadEngine}=require('./load');const DEG=180/Math.PI,G=9.81;const clamp=(v,a,b)=>v<a?a:v>b?b:v;const f=(x,d=2)=>(+x).toFixed(d);
function fresh(surface,tpl){const E=loadEngine();Object.assign(E.cfg,{surface,auto:true,steer:'direct',uniform:true,profile:false,driven:false,abs:false});E.VERT.amp=0;E.applySetupTemplate(tpl);E.selectTrack('rundkurs');return E;}
function setSpeed(E,v,gi){const S=E.S,CAR=E.CAR;S.vx=v;S.vy=0;S.r=0;S.delta=0;S.dComp=0;S.psi=0;S.x=0;S.y=0;const w=v/CAR.Rw;S.w=[w,w,w,w];S.gi=gi||3;S.rpm=w*CAR.gears[S.gi].r*CAR.final*9.55;S.we=S.rpm*0.10472;S.shiftLock=0.4;E.vertInit();}
function hold(E,vT,c){const e=vT-Math.hypot(E.S.vx,E.S.vy);c.I=clamp((c.I||0)+e*E.DT*0.6,-0.9,0.9);const u=0.35*e+c.I;E.IN.thr=clamp(u,0,1);E.IN.brk=clamp(-u*0.5,0,1);}
function skid(E){const S=E.S,L=E.CAR.a+E.CAR.b,vT=60/3.6;setSpeed(E,vT);const c={};for(let i=0;i<720;i++){hold(E,vT,c);E.step(E.DT);}let t=0,ayMax=0,inR=1e9,K=null,past=false;const lin=[];
  while(t<40){const d=0.5/DEG*t;E.IN.steer=d/E.CAR.maxSteer;hold(E,vT,c);E.step(E.DT);t+=E.DT;const ay=S.ay;if(ay>=0.3*G)past=true;if(!past&&ay>0.1*G)lin.push([ay,d]);if(ay>ayMax){ayMax=ay;inR=S.Fz[2];}if(ay<0.9*ayMax&&d*DEG>5)break;}
  const n=lin.length;let sx=0,sy=0,sxx=0,sxy=0;for(const [a,d] of lin){sx+=a;sy+=d;sxx+=a*a;sxy+=a*d;}K=((n*sxy-sx*sy)/(n*sxx-sx*sx)-L/(vT*vT))*G*DEG;return {ay:ayMax/G,inR,K};}
function brake(E){const S=E.S;setSpeed(E,100/3.6);const c={};for(let i=0;i<360;i++){hold(E,100/3.6,c);E.step(E.DT);}const x0=S.x,y0=S.y;E.IN.thr=0;E.IN.brk=1;let t=0,tF=null,tR=null;while(Math.hypot(S.vx,S.vy)>0.3&&t<9){E.step(E.DT);t+=E.DT;if(tF===null&&Math.min(S.kappa[0],S.kappa[1])<-0.9)tF=t;if(tR===null&&Math.min(S.kappa[2],S.kappa[3])<-0.9)tR=t;}return {d:Math.hypot(S.x-x0,S.y-y0),tF,tR};}
function launch(E){E.IN.thr=1;let t=0;while(t<16){E.step(E.DT);t+=E.DT;if(Math.hypot(E.S.vx,E.S.vy)>=100/3.6)return t;}return null;}
function catchS(E,vk){const S=E.S;setSpeed(E,vk/3.6);let t=0,bMax=0,rec=null;for(let i=0;i<Math.round(4/E.DT);i++){const b=Math.atan2(S.vy,Math.abs(S.vx));if(t<0.7){E.IN.steer=0.6;E.IN.thr=1;}else{E.IN.steer=clamp(1.2*b/E.CAR.maxSteer,-1,1);E.IN.thr=0;}E.step(E.DT);t+=E.DT;bMax=Math.max(bMax,Math.abs(b)*DEG);if(t>0.7&&rec===null&&Math.abs(b)*DEG<5&&bMax>10)rec=t-0.7;}return {bMax,rec};}
function stab(E,ayT,act){const S=E.S,vT=60/3.6;setSpeed(E,vT);const c={};for(let i=0;i<720;i++){hold(E,vT,c);E.step(E.DT);}E.IN.steer=((E.CAR.a+E.CAR.b)/(vT*vT)+(2/DEG)/G)*ayT*G/E.CAR.maxSteer;for(let i=0;i<1080;i++){hold(E,vT,c);E.step(E.DT);}const r0=S.r;let rMax=r0,bMax=0;for(let i=0;i<360;i++){E.IN.thr=act==='power'?1:0;E.IN.brk=0;E.step(E.DT);rMax=Math.max(rMax,S.r);bMax=Math.max(bMax,Math.abs(Math.atan2(S.vy,S.vx))*DEG);}return {dr:(rMax/r0-1)*100,bMax};}
console.log('template    surface | skidpad ay,max  inside-rear load  K °/g | 100–0 m  lock F/R s | 0–100 s | catch 40: β/t | lift-off Δr β | power Δr β');
for(const tpl of ['Gravel','Tarmac','RWD drift'])for(const surface of ['tarmac','gravel']){
  const s=skid(fresh(surface,tpl)),b=brake(fresh(surface,tpl)),l=launch(fresh(surface,tpl)),c=catchS(fresh(surface,tpl),40),lo=stab(fresh(surface,tpl),surface==='tarmac'?0.6:0.45,'lift'),po=stab(fresh(surface,tpl),0.45,'power');
  console.log(tpl.padEnd(11),surface.padEnd(7),'|',f(s.ay),'g',f(s.inR,0).padStart(6),'N',f(s.K,1).padStart(6),'|',f(b.d,1).padStart(6),' ',f(b.tF)+'/'+f(b.tR),' |',f(l),' |',f(c.bMax,0).padStart(3)+'°/'+(c.rec!==null?f(c.rec,1)+'s':'never'),' |',f(lo.dr,0).padStart(4)+'%',f(lo.bMax,0).padStart(3)+'°',' |',f(po.dr,0).padStart(4)+'%',f(po.bMax,0).padStart(3)+'°');
}
